[package]
name = "vaults"
version = "0.3.0"
edition = "2021"
rust-version = "1.63"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk-macros = "0.3"
once_cell = "1.5"
quick-error = "2.0.0"
strum = "0.24"
strum_macros = "0.24"
toml = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
adw = { version = "0.2", package = "libadwaita", features = ["v1_2"] }
gtk = { version = "0.5", package = "gtk4", features = ["v4_8"]}
